# -*- coding: utf-8 -*-
"""E-C0mmerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wU0IC6NScdBZiZeLPw4CWXsAl_i0jOBJ
"""

'''
PROJECT TITLE : E-Commerce Advanced Customer Behavior & Churn
AUTHOR/ CREATER: MR. VISHAL CHAUHAN (FUTURE DATA ANALYST OR PYTHON DEVELOPER)
TECH STACK : PYTHON, (Pandas, NumPy, Matplotlib, Seaborn), OOPs, Exceptions, Functional Programming
'''

import os
import sys
from datetime import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Concept No.1 :-OOPs (Object-Oriented Programming)
# let's create our own Cutom Exception with the use of Classes

class datapiplineError(Exception):
  '''handel datapipeline failure gracefully'''   # yaha humne khud ka ek datapipeline failure ka ek exception error create kiya hai.
  pass

class Ecommercedatapipeline:
  def __init__(self, n_customers=1500):
        self.n_customers = n_customers
        self.df = None  # now we just start our data structure process we should mention at this point our DataFrame is None to pandas
        print(f" Data Pipeline Initialized for {self.n_customers} customers.")



def generate_raw_data(self):
        try:
            np.random.seed(42)

            # Generating features
            customer_ids = [f"CUST-{i}" for i in range(1000, 1000 + self.n_customers)]
            ages = np.random.randint(18, 70, size=self.n_customers)
            genders = np.random.choice(['Male', 'Female', 'Other'], size=self.n_customers, p=[0.45, 0.50, 0.05])
            total_spend = np.random.uniform(10.0, 5000.0, size=self.n_customers).round(2)
            purchase_count = np.random.randint(1, 60, size=self.n_customers)

            # Creating dependency for Churn (Logic: high days since last purchase = high churn)
            days_since_last_purchase = np.random.randint(1, 365, size=self.n_customers)
            churn_probabilities = [1 / (1 + np.exp(-(days - 180)/30)) for days in days_since_last_purchase]
            churned = [np.random.choice(['Yes', 'No'], p=[p, 1-p]) for p in churn_probabilities]

            raw_data = {
                'CustomerID': customer_ids,
                'Age': ages,
                'Gender': genders,
                'TotalSpend': total_spend,
                'PurchaseCount': purchase_count,
                'DaysSinceLastPurchase': days_since_last_purchase,
                'Churned': churned
            }
            self.df = pd.DataFrame(raw_data) # Convert to DataFrame and assign to self.df
            print(f"Raw data generated for {self.n_customers} customers.")
            return self.df
        except Exception as e:
            raise datapiplineError(f"Failed to generate raw data: {e}") from e
            self.df = pd.DataFrame(raw_data)

class datapiplineError(Exception):
  '''handel datapipeline failure gracefully'''
  pass

class Ecommercedatapipeline:
  def __init__(self, n_customers=1500):
        self.n_customers = n_customers
        self.df = None
        print(f" Data Pipeline Initialized for {self.n_customers} customers.")

  def generate_raw_data(self):
        try:
            np.random.seed(42)

            # Generating features
            customer_ids = [f"CUST-{i}" for i in range(1000, 1000 + self.n_customers)]
            ages = np.random.randint(18, 70, size=self.n_customers)
            genders = np.random.choice(['Male', 'Female', 'Other'], size=self.n_customers, p=[0.45, 0.50, 0.05])
            total_spend = np.random.uniform(10.0, 5000.0, size=self.n_customers).round(2)
            purchase_count = np.random.randint(1, 60, size=self.n_customers)

            # Creating dependency for Churn
            days_since_last_purchase = np.random.randint(1, 365, size=self.n_customers)
            churn_probabilities = [1 / (1 + np.exp(-(days - 180)/30)) for days in days_since_last_purchase]
            churned = [np.random.choice(['Yes', 'No'], p=[p, 1-p]) for p in churn_probabilities]

            raw_data = {
                'CustomerID': customer_ids,
                'Age': ages,
                'Gender': genders,
                'TotalSpend': total_spend,
                'PurchaseCount': purchase_count,
                'DaysSinceLastPurchase': days_since_last_purchase,
                'Churned': churned
            }
            self.df = pd.DataFrame(raw_data)


            self.df.loc[self.df.sample(frac=0.05).index, 'TotalSpend'] = np.nan
            # Outlier injection
            self.df.loc[self.df.sample(n=5).index, 'TotalSpend'] = 99999.0

            print(" Step 1: Messy Raw Data Generated successfully.")
            return self.df

        except Exception as e:
            raise datapiplineError(f"Failed to generate raw data: {e}") from e

  def clean_and_transform(self):
      if self.df is None:
          raise datapiplineError("No data found! Run 'generate_raw_data()' first.")

      print("Step 2: Cleaning and Transforming data...")

      # Create a copy to avoid SettingWithCopyWarning
      df_cleaned = self.df.copy()

      # 1. Handling Missing Values (Imputing Median Spend based on Gender group)
      # Python Concept: Lambda function with Groupby
      df_cleaned['TotalSpend'] = df_cleaned.groupby('Gender')['TotalSpend'].transform(lambda x: x.fillna(x.median()))

      # 2. Outlier Removal using IQR (Interquartile Range) Method
      q1 = df_cleaned['TotalSpend'].quantile(0.25)
      q3 = df_cleaned['TotalSpend'].quantile(0.75)
      iqr = q3 - q1
      lower_bound = q1 - 1.5 * iqr
      upper_bound = q3 + 1.5 * iqr

      # Filtering out extreme outliers
      df_cleaned = df_cleaned[(df_cleaned['TotalSpend'] >= lower_bound) & (df_cleaned['TotalSpend'] <= upper_bound)]

      # 3. Feature Engineering: Average Order Value (AOV)
      df_cleaned['AOV'] = (df_cleaned['TotalSpend'] / df_cleaned['PurchaseCount']).round(2)

      # 4. Customer Segmentation using pd.cut (Binning)
      bins = [0, 500, 2000, float('inf')]
      labels = ['Low Value', 'Medium Value', 'High Value']
      df_cleaned['CustomerSegment'] = pd.cut(df_cleaned['TotalSpend'], bins=bins, labels=labels)

      self.df = df_cleaned # Update the class DataFrame with the cleaned version
      print("✓ Data cleaned, outliers removed, and features engineered.")
      return self.df


  def analyze_business_metrics(self):
      print("\n" + "="*50)
      print("          EXECUTIVE BUSINESS INSIGHTS REPORT       ")
      print("="*50)

      # KPI 1: Churn Rate Analysis
      churn_counts = self.df['Churned'].value_counts(normalize=True) * 100
      print(f"• Overall Customer Churn Rate: {churn_counts.get('Yes', 0):.2f}%")

      # KPI 2: Segment-wise Analytics (Aggregation)
      segment_summary = self.df.groupby('CustomerSegment').agg(
          Total_Revenue=('TotalSpend', 'sum'),
          Avg_Retention_Period=('DaysSinceLastPurchase', 'mean'),
          Total_Customers=('CustomerID', 'count')
      ).round(2)

      print("\n• Customer Segment Insights:")
      print(segment_summary)

      # KPI 3: Correlation matrix check
      correlation = self.df[['Age', 'TotalSpend', 'PurchaseCount', 'DaysSinceLastPurchase']].corr()
      print("\n• Correlation Matrix (Key Metrics):")
      print(correlation.round(2))

  def generate_dashboard(self):
      print(" Step 4: Generating Executive Visual Dashboard...")

      # Setting style
      sns.set_theme(style="darkgrid")
      fig, axes = plt.subplots(1, 2, figsize=(16, 6))

      # Chart 1: Boxenplot for Spend across Segments by Churn status
      sns.boxplot(
          ax=axes[0], data=self.df, x='CustomerSegment', y='TotalSpend',
          hue='Churned', palette='Set1'
      )
      axes[0].set_title('Revenue Distribution & Churn across Segments', fontsize=14, fontweight='bold')
      axes[0].set_xlabel('Customer Segment')
      axes[0].set_ylabel('Total Spend ($)')

      # Chart 2: Kernel Density Estimate (KDE) for Engagement
      sns.kdeplot(
          ax=axes[1], data=self.df, x='DaysSinceLastPurchase',
          hue='Churned', fill=True, common_norm=False, palette='coolwarm', alpha=0.5
      )
      axes[1].set_title('Customer Engagement vs Risk Zone (Churn)', fontsize=14, fontweight='bold')
      axes[1].set_xlabel('Days Since Last Purchase')
      axes[1].set_ylabel('Density Risk')

      plt.tight_layout()

      # Saving the artifact (Dashboard file)
      output_filename = 'ecommerce_customer_insights.png'
      plt.savefig(output_filename, dpi=300)
      print(f"✓ Dashboard saved successfully as '{output_filename}'!")
      plt.show()


if __name__ == "__main__":
    try:
        # Pipeline running smoothly
        pipeline = Ecommercedatapipeline(n_customers=2000)
        raw_df = pipeline.generate_raw_data()
        cleaned_df = pipeline.clean_and_transform()
        pipeline.analyze_business_metrics()
        pipeline.generate_dashboard()

    except datapiplineError as e:
        print(f"❌ Pipeline Failed: {e}", file=sys.stderr)
    except Exception as e:
        print(f"💥 Critical System Failure: {e}", file=sys.stderr)



